// Export utilities for saving analyses
import html2pdf from 'html2pdf.js';
import { marked } from 'marked';

/**
 * Download content as a file
 * @param {string} content - File content
 * @param {string} filename - Name of the file
 * @param {string} mimeType - MIME type
 */
export function downloadFile(content, filename, mimeType = 'text/plain') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
}

/**
 * Create safe filename from analysis prompt
 */
function createSafeFilename(prompt, extension) {
    const safeTitle = prompt
        .slice(0, 50)
        .replace(/[^a-zA-Z0-9\s-]/g, '')
        .replace(/\s+/g, '-')
        .toLowerCase();

    return `${safeTitle}-${Date.now()}.${extension}`;
}

/**
 * Export analysis as PDF
 * @param {Object} analysis - Analysis object
 */
export async function exportAsPDF(analysis) {
    console.log('Exporting PDF for analysis:', analysis);

    const date = new Date(analysis.createdAt).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });

    // Get the content - handle various formats
    let content = '';
    if (typeof analysis.result === 'string') {
        content = analysis.result;
    } else if (analysis.result?.content) {
        content = analysis.result.content;
    } else if (analysis.content) {
        content = analysis.content;
    }

    console.log('PDF content length:', content.length);

    if (!content || content.length === 0) {
        console.error('No content found for PDF export');
        alert('No content available to export');
        return null;
    }

    // Convert markdown to HTML
    const htmlContent = marked(content);

    // Create a styled container with inline styles (important for PDF rendering)
    const container = document.createElement('div');
    container.id = 'pdf-export-container';
    container.innerHTML = `
        <div style="
            font-family: Georgia, 'Times New Roman', serif;
            max-width: 170mm;
            margin: 0 auto;
            color: #1a1a2e;
            line-height: 1.6;
            font-size: 11pt;
        ">
            <div style="
                border-bottom: 2px solid #6366f1;
                padding-bottom: 15px;
                margin-bottom: 20px;
            ">
                <h1 style="
                    font-size: 18pt;
                    font-weight: 700;
                    color: #1a1a2e;
                    margin: 0 0 8px 0;
                ">${analysis.prompt}</h1>
                <div style="
                    font-size: 9pt;
                    color: #64748b;
                ">
                    Generated: ${date} • Depth: ${analysis.depth || 'standard'}
                </div>
            </div>
            <div class="pdf-content">
                ${htmlContent}
            </div>
            <div style="
                margin-top: 30px;
                padding-top: 15px;
                border-top: 1px solid #e2e8f0;
                font-size: 9pt;
                color: #94a3b8;
                text-align: center;
            ">
                Generated by DeepMind AI Analysis Platform
            </div>
        </div>
        <style>
            #pdf-export-container h1 { font-size: 16pt; color: #1a1a2e; margin-top: 20px; margin-bottom: 10px; page-break-after: avoid; }
            #pdf-export-container h2 { font-size: 14pt; color: #334155; margin-top: 18px; margin-bottom: 8px; page-break-after: avoid; }
            #pdf-export-container h3 { font-size: 12pt; color: #475569; margin-top: 15px; margin-bottom: 6px; page-break-after: avoid; }
            #pdf-export-container p { margin: 8px 0; text-align: justify; }
            #pdf-export-container ul, #pdf-export-container ol { margin: 8px 0; padding-left: 20px; }
            #pdf-export-container li { margin: 4px 0; }
            #pdf-export-container code { background: #f1f5f9; padding: 1px 4px; border-radius: 3px; font-family: 'Courier New', monospace; font-size: 10pt; }
            #pdf-export-container pre { background: #f1f5f9; padding: 10px; border-radius: 5px; overflow-x: auto; font-size: 9pt; white-space: pre-wrap; word-wrap: break-word; }
            #pdf-export-container blockquote { border-left: 3px solid #6366f1; margin: 10px 0; padding-left: 12px; color: #475569; font-style: italic; }
            #pdf-export-container strong { color: #1a1a2e; }
            #pdf-export-container table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 10pt; }
            #pdf-export-container th, #pdf-export-container td { border: 1px solid #e2e8f0; padding: 6px 8px; text-align: left; }
            #pdf-export-container th { background: #f8fafc; font-weight: 600; }
            #pdf-export-container tr { page-break-inside: avoid; }
        </style>
    `;

    // Add to DOM - must be visible for proper rendering
    container.style.position = 'fixed';
    container.style.top = '0';
    container.style.left = '0';
    container.style.width = '210mm';
    container.style.background = 'white';
    container.style.zIndex = '99999';
    container.style.padding = '20mm';
    container.style.boxSizing = 'border-box';
    document.body.appendChild(container);

    const filename = createSafeFilename(analysis.prompt, 'pdf');

    const opt = {
        margin: [15, 15, 15, 15],
        filename: filename,
        image: { type: 'jpeg', quality: 0.92 },
        html2canvas: {
            scale: 1,
            useCORS: true,
            logging: false,
            scrollY: 0,
            scrollX: 0,
            // Don't limit height - let it expand
            windowWidth: container.scrollWidth,
            windowHeight: container.scrollHeight
        },
        jsPDF: {
            unit: 'mm',
            format: 'a4',
            orientation: 'portrait',
            compress: true
        },
        pagebreak: {
            mode: ['css', 'legacy'],
            before: '.page-break-before',
            after: '.page-break-after',
            avoid: ['h1', 'h2', 'h3', 'h4', 'tr', 'li']
        }
    };

    try {
        // For large documents, use browser's print function which handles pagination better
        const contentLength = container.innerHTML.length;
        console.log('Content length:', contentLength);

        if (contentLength > 50000) {
            // Large document - use print dialog
            console.log('Large document detected, using print dialog');

            // Open a new window with the content
            const printWindow = window.open('', '_blank', 'width=800,height=600');
            printWindow.document.write(`
                <!DOCTYPE html>
                <html>
                <head>
                    <title>${analysis.prompt}</title>
                    <style>
                        @page { size: A4; margin: 20mm; }
                        @media print {
                            body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                            h1, h2, h3, h4 { page-break-after: avoid; }
                            tr, li { page-break-inside: avoid; }
                        }
                        body {
                            font-family: Georgia, 'Times New Roman', serif;
                            line-height: 1.6;
                            color: #1a1a2e;
                            font-size: 11pt;
                            max-width: 170mm;
                            margin: 0 auto;
                            padding: 20px;
                        }
                        h1 { font-size: 16pt; margin-top: 20px; page-break-after: avoid; }
                        h2 { font-size: 14pt; margin-top: 18px; page-break-after: avoid; }
                        h3 { font-size: 12pt; margin-top: 15px; page-break-after: avoid; }
                        p { margin: 8px 0; text-align: justify; }
                        ul, ol { padding-left: 20px; }
                        li { margin: 4px 0; }
                        code { background: #f1f5f9; padding: 1px 4px; border-radius: 3px; font-family: monospace; }
                        pre { background: #f1f5f9; padding: 10px; border-radius: 5px; white-space: pre-wrap; }
                        blockquote { border-left: 3px solid #6366f1; padding-left: 12px; margin: 10px 0; color: #475569; }
                        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
                        th, td { border: 1px solid #e2e8f0; padding: 6px 8px; }
                        th { background: #f8fafc; }
                        .header { border-bottom: 2px solid #6366f1; padding-bottom: 15px; margin-bottom: 20px; }
                        .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 9pt; }
                    </style>
                </head>
                <body>
                    ${container.innerHTML}
                </body>
                </html>
            `);
            printWindow.document.close();

            // Give it a moment to render, then print
            setTimeout(() => {
                printWindow.print();
                // Don't close immediately - let user save as PDF
            }, 500);

            document.body.removeChild(container);
            return filename;
        }

        // Small document - use html2pdf as before
        const worker = html2pdf().set(opt).from(container);
        await worker.toPdf().save();
        console.log('PDF saved successfully');
    } catch (err) {
        console.error('PDF generation error:', err);
        alert('PDF generation failed: ' + err.message);
    } finally {
        if (document.body.contains(container)) {
            document.body.removeChild(container);
        }
    }

    return filename;
}

/**
 * Export analysis as Markdown
 * @param {Object} analysis - Analysis object
 */
export function exportAsMarkdown(analysis) {
    const date = new Date(analysis.createdAt).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });

    const content = typeof analysis.result === 'string'
        ? analysis.result
        : analysis.result?.content || '';

    const mdContent = `# ${analysis.prompt}

**Date:** ${date}  
**Depth:** ${analysis.depth || 'standard'}  

---

${content}
`;

    const filename = createSafeFilename(analysis.prompt, 'md');
    downloadFile(mdContent, filename, 'text/markdown');
    return filename;
}

/**
 * Export analysis as JSON (for backup/restore)
 * @param {Object} analysis - Analysis object
 */
export function exportAsJSON(analysis) {
    const content = JSON.stringify(analysis, null, 2);
    const filename = createSafeFilename(analysis.prompt, 'json');
    downloadFile(content, filename, 'application/json');
    return filename;
}

/**
 * Export all analyses as a single JSON backup
 * @param {Array} analyses - Array of analysis objects
 */
export function exportAllAnalyses(analyses) {
    const backup = {
        exportedAt: new Date().toISOString(),
        version: '1.0',
        analyses
    };

    const content = JSON.stringify(backup, null, 2);
    const filename = `deepmind-backup-${Date.now()}.json`;

    downloadFile(content, filename, 'application/json');
    return filename;
}
